# curl -X POST http://localhost:8080/create_event?date=2019-10-08&text=event2
POST http://localhost:8080/create_event?date=2019-10-08&text=event2

###

# curl -X POST http://localhost:8080/update_event?date=2019-10-08&textOld=event2&text=event4
POST http://localhost:8080/update_event?date=2019-10-08&textOld=event2&text=event4

###

# curl -X POST http://localhost:8080/delete_event?date=2019-10-29&text=event2
POST http://localhost:8080/delete_event?date=2019-10-29&text=event2

###

# curl -X GET http://localhost:8080/events_for_day?date=2019-10-08
GET http://localhost:8080/events_for_day?date=2019-10-08

###

# curl -X GET http://localhost:8080/events_for_week?date=2019-10-07
GET http://localhost:8080/events_for_week?date=2019-10-07

###

# curl -X GET http://localhost:8080/events_for_month?month=2019-10
GET http://localhost:8080/events_for_month?month=2019-10


